#Jekill configuration
name: Santiago Lopez
description: academic and personal projects
markdown: kramdown
#theme: jekyll-theme-cayman
#title: Santiago Lopez
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
plugins: jekyll-include-cache
