#Jekill configuration
name: Santiago Lopez
description: academic and personal projects
markdown: kramdown
#theme: jekyll-theme-cayman
#title: Santiago Lopez
remote-theme: tianqi.name/jekyll-text-theme 
